on: [push]

jobs:
  start-selenoid:
    runs-on: ubuntu-latest
    name: Test SELENOID JOB
    steps:
    - uses: actions/checkout@v1
    - run: npm ci    
    - name: start selenoid
      uses: ./
    - name: is selenoid started?
      run: curl http://localhost:4444/status